// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYWajYKkAHgvnGbkEsNg4i8Rjz-L1vXVQ',
    appId: '1:330878038421:web:c350caec28c0ab7d76c69c',
    messagingSenderId: '330878038421',
    projectId: 'mobilechess-a8776',
    authDomain: 'mobilechess-a8776.firebaseapp.com',
    storageBucket: 'mobilechess-a8776.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYNE5um8R0OWOfXGIgsm2nRYAfzoa5D4A',
    appId: '1:330878038421:android:b7e5b30cd405b09c76c69c',
    messagingSenderId: '330878038421',
    projectId: 'mobilechess-a8776',
    storageBucket: 'mobilechess-a8776.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgPzM1dN7eFDdOYWFjhHu1IGNnPID_jNg',
    appId: '1:330878038421:ios:4ca909e01ada851f76c69c',
    messagingSenderId: '330878038421',
    projectId: 'mobilechess-a8776',
    storageBucket: 'mobilechess-a8776.appspot.com',
    iosBundleId: 'com.example.chessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgPzM1dN7eFDdOYWFjhHu1IGNnPID_jNg',
    appId: '1:330878038421:ios:4ca909e01ada851f76c69c',
    messagingSenderId: '330878038421',
    projectId: 'mobilechess-a8776',
    storageBucket: 'mobilechess-a8776.appspot.com',
    iosBundleId: 'com.example.chessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYWajYKkAHgvnGbkEsNg4i8Rjz-L1vXVQ',
    appId: '1:330878038421:web:30adfc24359bf27576c69c',
    messagingSenderId: '330878038421',
    projectId: 'mobilechess-a8776',
    authDomain: 'mobilechess-a8776.firebaseapp.com',
    storageBucket: 'mobilechess-a8776.appspot.com',
  );
}
